server:
    port: 8081
    context-path: /ic-iot

logging:
    level:
        tk.mybatis: TRACE

spring:
    datasource:
        url: jdbc:mysql://localhost/shop?useUnicode=true&characterEncoding=utf-8
        username: root
        spassword:
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
  config-location: classpath:mybatis-config.xml

